format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$python\
$line_break\
$character"""
right_format = """$cmd_duration"""

palette = "catppuccin_macchiato"

[directory]
style = "blue"

[character]
success_symbol = "[❯](lavender2)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](peach)"
vimcmd_visual_symbol = "[❮](peach)"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[git_branch]
style = "bold green"
format = " [$symbol$branch(:$remote_branch)]($style) "

[git_status]
style = "bold yellow"

[python]
style = "bold peach"
format = '[(\($virtualenv\) )]($style)'

[hostname]
ssh_only = true
style = "blue"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
lavender2 = "#ba88f7"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
