
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
  { on = [ "g", "h" ],       run = "cd ~",             desc = "Go home" },
	{ on = [ "g", "c" ],       run = "cd ~/.config",     desc = "Goto ~/.config" },
	{ on = [ "g", "d" ],       run = "cd ~/.dotfiles",   desc = "Goto ~/.dotfiles" },
	{ on = [ "g", "n" ],       run = "cd ~/.dotfiles/nvim/.config/nvim",   desc = "Goto nvim config" },
	{ on = [ "g", "p" ],       run = "cd ~/programs",   desc = "Goto ~/programs" },
	{ on = [ "g", "<Space>" ], run = "cd --interactive", desc = "Jump interactively" },
	{ on = [ "v" ], run = "shell --block nvim", desc = "Run neovim" },
]
